---

- name: kill user [{{ greenplum_admin_user }}] all process
  shell: pkill -u {{ greenplum_admin_user }}
  ignore_errors: true

- name: remove tmp files in tmp directory
  shell:  rm -rf /tmp/.s.PGSQL.* 

- name: erase greenplum package
  yum:
    name: open-source-greenplum-db-6
    state: absent
    
- name: delete greenplum install and data files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
  - '{{ greenplum_data_directory }}'
  - '/home/{{ greenplum_admin_user }}'

- name: delete greenplum user
  user:
    name: "{{ greenplum_admin_user }}"
    state: absent
